Identity:
  GenerateNewKey: true
#  LoadKeyFromFile: file.key
#  SaveKeyToFile: file.key

Server:
  port: 9001

Redis:
  Host: 127.0.0.1
  Tl2NlChannel: gp2p_tl2nl2

ProtocolSettings:
  Recommendation:
    Timeout: 10s
  Intelligence:
    MaxTtl: 5
    Ttl: 5
    RootTimeout: 10s
    MaxRootTimeout: 10s

PeerDiscovery:
  ListOfMultiAddresses:
   - "/ip4/127.0.0.1/udp/9000/quic 12D3KooWNDWAZ5zMzqzAERLE2f8R5TZFAqYNLffSPLW8NuEnUoGo"