Identity:
  GenerateNewKey: true
#  LoadKeyFromFile: file.key
#  SaveKeyToFile: file.key

Server:
  port: 9001

Redis:
  Host: 127.0.0.1
  Tl2NlChannel: gp2p_tl2nl2

ProtocolSettings:
  Recommendation:
    Timeout: 10s

PeerDiscovery:
  ListOfMultiAddresses:
   - "/ip4/192.168.88.43/udp/9000/quic 12D3KooWS5G6m124xijU3vV6UvPbMs5H8iMBaAF4q4Zwvd2SnQJq"