Identity:
  GenerateNewKey: true
#  LoadKeyFromFile: /home/yourmother/moje/projects/p2pnetwork/dev/peer1/key.priv
#  SaveKeyToFile: file.key

Server:
  port: 9006

Redis:
  Host: 127.0.0.1
  Tl2NlChannel: gp2p_tl2nl6

ProtocolSettings:
  Recommendation:
    Timeout: 10s
  Intelligence:
    MaxTtl: 5
    Ttl: 5
    RootTimeout: 10s
    MaxRootTimeout: 10s

PeerDiscovery:
  ListOfMultiAddresses:
   - '/ip4/127.0.0.1/udp/9001/quic 12D3KooWLDCxxP6PAKG6NUYWs16VbSZhQNHY361otSmauvVnXV4g'
#   - "/ip4/127.0.0.1/udp/9002/quic 12D3KooWFTf9mXfR5yN1oPv7wPNGMq7DfgPPmep9hREy5syuZ6ug"