Identity:
  GenerateNewKey: true
#  LoadKeyFromFile: file.key
#  SaveKeyToFile: file.key

Server:
  port: 9001

Redis:
  Host: 127.0.0.1
  Tl2NlChannel: gp2p_tl2nl2


PeerDiscovery:
  ListOfMultiAddresses:
   - "/ip4/192.168.88.43/udp/9000/quic 12D3KooWE6sudG8bndFCF9VJqPTGvPRMVLAAizwbyK1Lcx3bSjAq"