Identity:
  GenerateNewKey: true
#  LoadKeyFromFile: file.key
#  SaveKeyToFile: file.key

Server:
  port: 9001

Redis:
  Host: 127.0.0.1
  Tl2NlChannel: gp2p_tl2nl1

ProtocolSettings:
  Recommendation:
    Timeout: 10s
  Intelligence:
    MaxTtl: 5
    Ttl: 5
    RootTimeout: 10s
    MaxRootTimeout: 10s

PeerDiscovery:
  ListOfMultiAddresses:
   - "/ip4/10.0.0.40/udp/9000/quic 12D3KooWSndoeEM8duZwTbJU1FCZSw3tMqKjFMCR9BfTweVSNPCx"
#   - "/ip4/127.0.0.1/udp/9002/quic 12D3KooWFTf9mXfR5yN1oPv7wPNGMq7DfgPPmep9hREy5syuZ6ug"