# This peer has connection string:
# /ip4/192.168.0.10/udp/9001/quic 12D3KooWNxiCsZFyUFpLFNKDLEQDUK36myifqufnnveK1jycMoJ8

IdentityConfig:
  GenerateNewKey: false
  LoadKeyFromFile: ./vol/key.priv

Server:
  port: 9001

PeerDiscovery:
  ListOfMultiAddresses:
    - "/ip4/192.168.0.30/udp/9003/quic 12D3KooWP62GoxVhGSSAriPhtam7Ris6XULUgk9uh5uGcXbYcEaP"