# This peer has connection string:
# /ip4/192.168.0.30/udp/9003/quic 12D3KooWP62GoxVhGSSAriPhtam7Ris6XULUgk9uh5uGcXbYcEaP

Identity:
  GenerateNewKey: false
  LoadKeyFromFile: ./vol/key.priv

Server:
  port: 9003
  Host: 192.168.0.30
  DhtServerMode: true

Redis:
  Host: 192.168.0.69
  Tl2NlChannel: gp2p_tl2nl3

PeerDiscovery:
  DisableBootstrappingNodes: true
  ListOfMultiAddresses:
#    - "/ip4/192.168.0.10/udp/9001/quic 12D3KooWNxiCsZFyUFpLFNKDLEQDUK36myifqufnnveK1jycMoJ8"
    - "/ip4/192.168.0.20/udp/9002/quic 12D3KooWLDCxxP6PAKG6NUYWs16VbSZhQNHY361otSmauvVnXV4g"