# This peer has connection string:
# /ip4/192.168.0.30/udp/9003/quic 12D3KooWP62GoxVhGSSAriPhtam7Ris6XULUgk9uh5uGcXbYcEaP

Identity:
  GenerateNewKey: false
  LoadKeyFromFile: ./vol/key.priv

Server:
  port: 9003

Redis:
  Host: 192.168.0.69
  Channels:
    Tl2nlAlarmChannel: tl2nlAlarm3
    Nl2tlAlarmChannel: nl2tlAlarm3

PeerDiscovery:
  ListOfMultiAddresses:
#    - "/ip4/192.168.0.10/udp/9001/quic 12D3KooWNxiCsZFyUFpLFNKDLEQDUK36myifqufnnveK1jycMoJ8"
    - "/ip4/192.168.0.20/udp/9002/quic 12D3KooWLDCxxP6PAKG6NUYWs16VbSZhQNHY361otSmauvVnXV4g"