# This peer has connection string:
# /ip4/192.168.0.20/udp/9002/quic 12D3KooWLDCxxP6PAKG6NUYWs16VbSZhQNHY361otSmauvVnXV4g

Identity:
  GenerateNewKey: false
  LoadKeyFromFile: ./vol/key.priv

Server:
  port: 9002
  Host: 192.168.0.20
  DhtServerMode: true

Redis:
  Host: 192.168.0.69
  Tl2NlChannel: gp2p_tl2nl2

PeerDiscovery:
  DisableBootstrappingNodes: true
  ListOfMultiAddresses:
    - "/ip4/192.168.0.10/udp/9001/quic 12D3KooWNxiCsZFyUFpLFNKDLEQDUK36myifqufnnveK1jycMoJ8"