# This peer has connection string:
# /ip4/192.168.0.40/udp/9004/quic 12D3KooWBQZzUSWRcYSR7erwqHVg3P9wwu7pUvJgC2BSFxgY7jEG

Identity:
  GenerateNewKey: false
  LoadKeyFromFile: ./vol/key.priv

Server:
  port: 9004

Redis:
  Host: 192.168.0.69
  Tl2NlChannel: gp2p_tl2nl4

ProtocolSettings:
  Recommendation:
    Timeout: 10s
  Intelligence:
    MaxTtl: 5
    Ttl: 5
    RootTimeout: 10s
    MaxRootTimeout: 10s

PeerDiscovery:
  ListOfMultiAddresses:
    - "/ip4/192.168.0.10/udp/9001/quic 12D3KooWNxiCsZFyUFpLFNKDLEQDUK36myifqufnnveK1jycMoJ8"
    - "/ip4/192.168.0.20/udp/9002/quic 12D3KooWLDCxxP6PAKG6NUYWs16VbSZhQNHY361otSmauvVnXV4g"
    - "/ip4/192.168.0.30/udp/9003/quic 12D3KooWP62GoxVhGSSAriPhtam7Ris6XULUgk9uh5uGcXbYcEaP"